#!/bin/bash

set -e

echo ""
echo "starting tdexd"

docker run -it -d --name tdexd -v $(pwd)/tdexd:/.tdex-daemon --network="host" -e TDEX_NETWORK="regtest" -e TDEX_BASE_ASSET="5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225" -e TDEX_EXPLORER_ENDPOINT="http://127.0.0.1:3001" -e TDEX_NO_MACAROONS=true ghcr.io/tdex-network/tdexd:latest

echo ""
echo "init wallet"

tdex='docker exec -it tdexd tdex '
$tdex config init --network "regtest" --explorer_url "http://localhost:3001" --no_macaroons
$tdex init --seed "wrestle actress dirt spice ridge bone depart leisure fruit shoot elite mistake play supply inhale million tennis harvest merit anchor shaft desert organ salute" --password secret &>/dev/null

echo ""
echo "unlocking wallet"

$tdex unlock --password secret &>/dev/null

addressfee=$($tdex depositfee | jq -r '.address_with_blinding_key[0].address')

echo ""
echo "fee address: ${addressfee}"

feetxid1=$(curl -s -X POST -H 'Content-Type: application/json' -d '{"address":"'$addressfee'", "amount": 0.1}' "http://localhost:3001/faucet")
feetxid2=$(curl -s -X POST -H 'Content-Type: application/json' -d '{"address":"'$addressfee'", "amount": 0.1}' "http://localhost:3001/faucet")
feetxid3=$(curl -s -X POST -H 'Content-Type: application/json' -d '{"address":"'$addressfee'", "amount": 0.1}' "http://localhost:3001/faucet")

sleep 5

feevout1=$(curl -s -X GET "http://localhost:3001/tx/'$feetxid1'" | jq -r '.details[0].vout')
feevout2=$(nigiri rpc --liquid gettransaction $feetxid2 | jq -r '.details[0].vout')
feevout3=$(nigiri rpc --liquid gettransaction $feetxid3 | jq -r '.details[0].vout')

$tdex claimfee --outpoints '[{"hash":"'$feetxid1'", "index":'$feevout1'}, {"hash":"'$feetxid2'", "index":'$feevout2'}, {"hash":"'$feetxid3'", "index":'$feevout3'}]'
sleep 1

addressmarket=$($tdex depositmarket | jq -r '.addresses[0]')

echo ""
echo "market address: ${addressmarket}"

btctxid=$(nigiri faucet --liquid $addressmarket 10 | grep '^txId: ' | cut -d ':' -f 2 | tr -d ' ')
sleep 5

btcvout=$(nigiri rpc --liquid gettransaction $btctxid | jq -r '.details[0].vout')

echo "market base outpoint: ${btctxid} ${btcvout}"

addressresponse=$(curl -s -X GET http://localhost:3001/getnewaddress)
addressnigiri=$(echo $addressresponse | jq -r '.address')

mintresponse=$(curl -s -X POST -H 'Content-Type: application/json' -d '{"address":"'$addressnigiri'", "amount": 500000, "name": "Liquid Tether", "ticker":"USDt"}' "http://localhost:3001/mint")
sleep 5

shitcoin=$(echo $mintresponse | jq -r '.asset')

shittxid1=$(nigiri faucet --liquid $addressmarket 100000 $shitcoin | grep '^txId: ' | cut -d ':' -f 2 | tr -d ' ')
shittxid2=$(nigiri faucet --liquid $addressmarket 100000 $shitcoin | grep '^txId: ' | cut -d ':' -f 2 | tr -d ' ')
shittxid3=$(nigiri faucet --liquid $addressmarket 100000 $shitcoin | grep '^txId: ' | cut -d ':' -f 2 | tr -d ' ')
sleep 5

shitvout1=$(nigiri rpc --liquid gettransaction $shittxid1 | jq -r '.details[0].vout')
shitvout2=$(nigiri rpc --liquid gettransaction $shittxid2 | jq -r '.details[0].vout')
shitvout3=$(nigiri rpc --liquid gettransaction $shittxid3 | jq -r '.details[0].vout')

echo "market quote asset: ${shitcoin}"
#echo "market quote outpoint: ${shittxid1} ${shitvout}"

$tdex config set base_asset 5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225 &>/dev/null
$tdex config set quote_asset $shitcoin &>/dev/null

$tdex claimmarket --outpoints '[{"hash":"'$btctxid'", "index":'$btcvout'}, {"hash":"'$shittxid1'", "index":'$shitvout1'}, {"hash":"'$shittxid2'", "index":'$shitvout2'}, {"hash":"'$shittxid3'", "index":'$shitvout3'}]'
sleep 1

echo ""
echo "opening market"
$tdex open

echo '{"market": {"baseAsset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225","quoteAsset": "'$shitcoin'"}} ' >./test/fixtures/trade.integration.json
